# Generated by Django 5.0.1 on 2026-03-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.CharField(max_length=500)),
                ('class_id', models.IntegerField(null=True)),
                ('class_name', models.CharField(blank=True, max_length=200)),
                ('class_name_ru', models.CharField(blank=True, max_length=200)),
                ('confidence', models.FloatField(null=True)),
                ('top3', models.JSONField(default=list)),
                ('mask_url', models.CharField(blank=True, max_length=500)),
                ('overlay_url', models.CharField(blank=True, max_length=500)),
                ('area_percent', models.FloatField(null=True)),
                ('contour_count', models.IntegerField(null=True)),
                ('gradcam_url', models.CharField(blank=True, max_length=500)),
                ('rag_description', models.TextField(blank=True)),
                ('report_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
